In [2]:
import numpy as np

def gram_schmidt_qr(mat):
    rows, cols = mat.shape
    Q_temp = np.zeros((rows, cols)) 
    upper = np.zeros((cols, cols)) 
    
    for col in range(cols):
        vec = mat[:, col]
        for prev_col in range(col):
            proj_coeff = np.dot(Q_temp[:, prev_col], mat[:, col])
            upper[prev_col, col] = proj_coeff
            vec -= proj_coeff * Q_temp[:, prev_col]

        norm_val = np.linalg.norm(vec)
        upper[col, col] = norm_val
        if norm_val > 1e-10:
            Q_temp[:, col] = vec / norm_val

    return Q_temp, upper

example= np.array([
    [1, 2, 4],
    [3, 8, 5],
    [2, 6, 13]
], dtype=float)
orthogonal, upper_tri = gram_schmidt_qr(example)


print("\nOrthogonal Matrix (Q):")
print(orthogonal)
print("\nUpper Matrix (R):")
print(upper_tri)

# Verify the result
reconstructed = np.dot(orthogonal, upper_tri)
print("\nReconstructed Matrix (QR):")
print(reconstructed)



Orthogonal Matrix (Q):
[[ 0.26726124 -0.77151675  0.57735027]
 [ 0.80178373 -0.15430335 -0.57735027]
 [ 0.53452248  0.6172134   0.57735027]]

Upper Matrix (R):
[[ 3.74165739 10.15592719 12.02675589]
 [ 0.          0.9258201   4.16619045]
 [ 0.          0.          6.92820323]]

Reconstructed Matrix (QR):
[[ 1.  2.  4.]
 [ 3.  8.  5.]
 [ 2.  6. 13.]]
